# Generated by Django 2.1.3 on 2020-01-28 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myturkishiid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertdesc',
            old_name='name',
            new_name='advertTitle',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='advertTitle',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='featureTitle',
        ),
    ]
