# Generated by Django 2.1.3 on 2020-01-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myturkishiid', '0005_advert_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Kod'),
        ),
    ]
