# Generated by Django 2.1.3 on 2019-09-09 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Yaşadığı Şehir')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='İlçe')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inoks.City', verbose_name='İl')),
            ],
        ),
        migrations.CreateModel(
            name='earningPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payedDate', models.DateTimeField(verbose_name='Ödeme Tarihi')),
                ('paymentTotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ödeme Tutarı')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Meslekler')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('url', models.CharField(blank=True, max_length=120, null=True)),
                ('is_parent', models.BooleanField(default=True)),
                ('is_show', models.BooleanField(default=True)),
                ('fa_icon', models.CharField(blank=True, max_length=120, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inoks.Menu')),
                ('permission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MenuPermission', to='auth.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='MenuAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('url', models.CharField(blank=True, max_length=120, null=True)),
                ('is_parent', models.BooleanField(default=True)),
                ('is_show', models.BooleanField(default=True)),
                ('fa_icon', models.CharField(blank=True, max_length=120, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inoks.MenuAdmin')),
                ('permission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuadmin', to='auth.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Sipariş Adeti')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('sponsor', models.TextField(blank=True, null=True, verbose_name='Sponsor')),
                ('payment_type', models.CharField(choices=[('Kapıda Ödeme', 'Kapıda Ödeme'), ('Kredi Kartı', 'Kredi Kartı'), ('Havale/EFT', 'Havale/EFT')], default='Kapıda Ödeme', max_length=128, verbose_name='Ödeme Türü')),
                ('isContract', models.BooleanField(default=False)),
                ('isApprove', models.BooleanField(default=False)),
                ('isPayed', models.BooleanField(default=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inoks.City', verbose_name='İl')),
                ('district', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inoks.District', verbose_name='İlçe')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSituations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=18500, null=True, verbose_name='Sipariş Durumları')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Ürün Resmi')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Ürün Adı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discountPrice', models.CharField(blank=True, max_length=120, null=True, verbose_name='İndirimli Fiyatı')),
                ('stock', models.CharField(blank=True, max_length=120, null=True, verbose_name='Stok Adeti')),
                ('discountStartDate', models.DateField(null=True, verbose_name='İndirim Başlama Tarihi')),
                ('discountFinishDate', models.DateField(null=True, verbose_name='İndirim Bitiş Tarihi')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Ürün Bilgileri')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=18500, null=True, verbose_name='Ürün Kategorisi')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', models.ImageField(blank=True, default='profile/user.png', null=True, upload_to='profile/', verbose_name='Profil Resmi')),
                ('tc', models.CharField(max_length=11, unique=True, verbose_name='T.C. Kimlik Numarası')),
                ('birthDate', models.DateField(null=True, verbose_name='Doğum Tarihi')),
                ('mobilePhone', models.CharField(max_length=11, verbose_name='Telefon Numarası')),
                ('address', models.TextField(verbose_name='Adres')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('gender', models.CharField(choices=[('Seçiniz', 'Seçiniz'), ('Erkek', 'Erkek'), ('Kadın', 'Kadın')], default='Seçiniz', max_length=128, verbose_name='Cinsiyeti')),
                ('educationLevel', models.CharField(choices=[('Seçiniz', 'Seçiniz'), ('İlkokul', 'İlkokul'), ('Lise', 'Lise'), ('Lisans', 'Lisans'), ('Yüksek Lisans', 'Yüksek Lisans'), ('Okumadı', 'Okumadı')], default='Seçiniz', max_length=128, verbose_name='Eğitim Düzeyi')),
                ('isApprove', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=False)),
                ('isContract', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inoks.City', verbose_name='İl')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inoks.District', verbose_name='İlçe')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inoks.Job', verbose_name='Meslek')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp', to='inoks.Profile', verbose_name='Sponsor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderQuantity', models.TextField(blank=True, null=True, verbose_name='İade Miktarı')),
                ('refundDate', models.DateTimeField(auto_now_add=True, verbose_name='İade Tarihi')),
                ('isOpen', models.CharField(choices=[('Evt', 'Evet'), ('Hayır', 'Hayır')], default='Hayır', max_length=128, verbose_name='Cinsiyeti')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inoks.Order', verbose_name='Sipariş Numarası')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inoks.Product', verbose_name='Ürün Adı')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inoks.Profile', verbose_name='Üye Adı')),
            ],
        ),
        migrations.CreateModel(
            name='RefundSituations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=18500, null=True, verbose_name='İade Durumları')),
            ],
        ),
        migrations.AddField(
            model_name='refund',
            name='refundSituations',
            field=models.ManyToManyField(to='inoks.RefundSituations'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='inoks.ProductCategory'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_situations',
            field=models.ManyToManyField(default='Ödeme Bekliyor', to='inoks.OrderSituations'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='inoks.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inoks.Profile', verbose_name='Üye Adı'),
        ),
        migrations.AddField(
            model_name='earningpayments',
            name='payer_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer_profile', to='inoks.Profile', verbose_name='Ödeme Yapan'),
        ),
        migrations.AddField(
            model_name='earningpayments',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='inoks.Profile', verbose_name='Ödeme Alan'),
        ),
    ]
