# Generated by Django 2.2.1 on 2019-07-26 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Yaşadığı Şehir')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='İlçe')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Meslekler')),
            ],
        ),
        migrations.CreateModel(
            name='OrderSituations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=18500, null=True, verbose_name='Sipariş Durumları')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=18500, null=True, verbose_name='Ürün Kategorisi')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Profil Resmi')),
                ('tc', models.CharField(blank=True, max_length=11, null=True, verbose_name='T.C. Kimlik Numarası')),
                ('birthDate', models.DateField(null=True, verbose_name='Doğum Tarihi')),
                ('mobilePhone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefon Numarası')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('gender', models.CharField(choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın')], default='Erkek', max_length=128, verbose_name='Cinsiyeti')),
                ('educationLevel', models.CharField(choices=[('İlkokul', 'İlkokul'), ('Lise', 'Lise'), ('Lisans', 'Lisans'), ('Yüksek Lisans', 'Yüksek Lisans'), ('Okumadı', 'Okumadı')], default='Lisans', max_length=128, verbose_name='Eğitim Düzeyi')),
                ('sponsor', models.CharField(blank=True, max_length=128, null=True, verbose_name='Sponsor Kodu')),
                ('isApprove', models.BooleanField(default=False)),
                ('isContract', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inoks.City', verbose_name='İl')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inoks.District', verbose_name='İlçe')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inoks.Job', verbose_name='Meslek')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Ürün Resmi')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Ürün Adı')),
                ('price', models.CharField(max_length=120, verbose_name='Ürün Fiyatı')),
                ('discountPrice', models.CharField(blank=True, max_length=120, null=True, verbose_name='İndirimli Fiyatı')),
                ('stock', models.CharField(blank=True, max_length=120, null=True, verbose_name='Stok Adeti')),
                ('discountStartDate', models.DateField(null=True, verbose_name='İndirim Başlama Tarihi')),
                ('discountFinishDate', models.DateField(null=True, verbose_name='İndirim Bitiş Tarihi')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Ürün Bilgileri')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('category', models.ManyToManyField(to='inoks.ProductCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=11, null=True, verbose_name='Sipariş Adeti')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('sponsor', models.TextField(blank=True, null=True, verbose_name='Sponsor')),
                ('payment_type', models.CharField(choices=[('Kapıda Ödeme', 'Kapıda Ödeme'), ('Kredi Kartı', 'Kredi Kartı'), ('Havale/EFT', 'Havale/EFT')], default='Kapıda Ödeme', max_length=128, verbose_name='Ödeme Türü')),
                ('isContract', models.BooleanField(default=False)),
                ('isApprove', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inoks.City', verbose_name='İl')),
                ('district', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inoks.District', verbose_name='İlçe')),
                ('order_situations', models.ManyToManyField(to='inoks.OrderSituations')),
                ('product', models.ManyToManyField(to='inoks.Product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inoks.Profile', verbose_name='Üye Adı')),
            ],
        ),
    ]
