# Generated by Django 2.2.1 on 2019-07-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inoks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundSituations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=18500, null=True, verbose_name='İade Durumları')),
            ],
        ),
    ]
