# Generated by Django 2.1.3 on 2019-09-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inoks', '0002_auto_20190912_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=8, null=True),
        ),
    ]
