# Generated by Django 2.2.1 on 2019-07-27 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inoks', '0002_refundsituations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderQuantity', models.TextField(blank=True, null=True, verbose_name='İade Miktarı')),
                ('refundDate', models.DateTimeField(auto_now_add=True, verbose_name='İade Tarihi')),
                ('isOpen', models.CharField(choices=[('Evt', 'Evet'), ('Hayır', 'Hayır')], default='Hayır', max_length=128, verbose_name='Cinsiyeti')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inoks.Order', verbose_name='Sipariş Numarası')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inoks.Product', verbose_name='Ürün Numarası')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inoks.Profile', verbose_name='Üye Numarası')),
                ('refundSituations', models.ManyToManyField(to='inoks.RefundSituations')),
            ],
        ),
    ]
