# Generated by Django 2.1.3 on 2019-09-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inoks', '0003_order_totalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImage', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='Ürün Resmi')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='productImage',
        ),
        migrations.AddField(
            model_name='product',
            name='productImage',
            field=models.ManyToManyField(blank=True, null=True, to='inoks.ProductImage', verbose_name='Ürün Resmi'),
        ),
    ]
