# Generated by Django 2.2.1 on 2019-07-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inoks', '0004_auto_20190727_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
