# Generated by Django 2.1.3 on 2019-09-16 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inoks', '0004_auto_20190912_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp', to='inoks.Profile', verbose_name='Sponsor'),
        ),
    ]
