# Generated by Django 2.2.1 on 2019-08-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inoks', '0005_profile_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_situations',
            field=models.ManyToManyField(default='Ödeme Bekliyor', to='inoks.OrderSituations'),
        ),
    ]
