# Generated by Django 2.2.1 on 2019-08-02 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inoks', '0006_auto_20190802_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Kayıt Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='modificationDate',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
    ]
