# Generated by Django 2.2.1 on 2019-08-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inoks', '0007_auto_20190802_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isPayed',
            field=models.BooleanField(default=False),
        ),
    ]
