# Generated by Django 2.2.1 on 2019-08-07 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inoks', '0008_order_ispayed'),
    ]

    operations = [
        migrations.CreateModel(
            name='earningPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payedDate', models.DateTimeField(verbose_name='Ödeme Tarihi')),
                ('paymentTotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ödeme Tutarı')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('modificationDate', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('payer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer_profile', to='inoks.Profile', verbose_name='Ödeme Yapan')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='inoks.Profile', verbose_name='Ödeme Alan')),
            ],
        ),
    ]
