# Generated by Django 2.2.1 on 2019-08-08 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inoks', '0009_earningpayments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp', to='inoks.Profile', verbose_name='Sponsor'),
        ),
    ]
