# Generated by Django 2.2.1 on 2019-08-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inoks', '0010_auto_20190808_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inoks.City', verbose_name='İl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='cityId',
            field=models.IntegerField(blank=True, null=True, verbose_name='İl Adı'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(blank=True, default='profile/user.png', null=True, upload_to='profile/', verbose_name='Profil Resmi'),
        ),
    ]
