# Generated by Django 2.2.1 on 2019-08-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inoks', '0012_remove_district_cityid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
