# Generated by Django 2.2.1 on 2019-08-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inoks', '0014_auto_20190814_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sipariş Adeti'),
        ),
    ]
